apiVersion: apps/v1
kind: Deployment
metadata:
  name: tic-tac-toe-app-deployment
  labels:
    app: tic-tac-toe-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tic-tac-toe-app
  template:
    metadata:
      labels:
        app: tic-tac-toe-app
    spec:
      imagePullSecrets:
      - name: github-container-registry
      containers:
        - name: tic-tac-toe-container
          image: ghcr.io/sanchit940/argocd-k8s-deployments:fa09c596f71376e67679d24e2bfca54459c54365
          ports:
          - containerPort: 80
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
