apiVersion: v1
kind: Deployment
metadata:
  name: tic-tac-toe-app-deployment
  labels:
    app: tic-tac-toe-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tic-tac-toe-app
  template:
    metadata:
      labels:
        app: tic-tac-toe-app
    spec:
      containers:
        - name: tic-tac-toe-container
          image: ghcr.io/sanchit940/argocd-k8s-deployments:7d42ebd8c7aba01ddb7fd73c5deb0157978478eb
          ports:
          - containerPort: 80
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
