name: CI-CD pipleine
on:
  push:

    branches:
      [main]
    paths-ignore:
      - 'README.md'

jobs:
  Unit-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node-js
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test || echo "No test found will add it later"

  Linting:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v6

        - name: Set up Node-js
          uses: actions/setup-node@v6
          with:
            node-version: 20

        - name: Install dependencies
          run: npm install

        - name: Run linting
          run: npm run lint

  Build: 
    runs-on: ubuntu-latest
    needs: [Unit-Test, Linting]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node-js
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: install dependencies
        run: npm install

      - name: Build project
        run: npm run build
      
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-file
          path: dist/

  Docker:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      
      - name: download build arifacts
        uses: actions/download-artifact@v4
        with:
          name: build-file
          path: dist/

      - name: login to the registery
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: |
           ghcr.io/${{ github.repository }}:${{ github.sha }}
           ghcr.io/${{ github.repository }}:latest
          load: true

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.33.1
        with: 
          image-ref: ghcr.io/${{ github.repository }}:${{ github.sha }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
           ghcr.io/${{ github.repository }}:${{ github.sha }}
           ghcr.io/${{ github.repository }}:latest
  
  Update-Deployment:
    runs-on: ubuntu-latest
    needs: [Docker]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.TOKEN }}

      - name: Setup Git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
        
  
      - name: update deployment file
        env:
          IMAGE_TAG: ${{ github.sha }}
          github_repository: ${{ github.repository }}

        run: |
          sed -i "s|image: ghcr.io/.*|image: ghcr.io/${{ github.repository }}:${{ github.sha }}|g" kubernetes/deployment.yaml

      - name: Commit and push changes
        run: |
          git add kubernetes/deployment.yaml
          git commit -m "Update Kubernetes deployment with new image tag: ${{ github.sha }} [skip ci]"
          git push
